name: '#GoldMember'
favicon: null
layout_spectrum: 0.9919441
typography_spectrum: 0.1390978
title: 'Team #GoldMember Blog, from Bronze Software Labs.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0A0A0A'
    - '#DC2305'
    - '#CDCDD5'
    - '#416B83'
    - '#AF853B'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.7700354
  rhythmicContrast: 0.03674091
purpose: []
