name: '#GoldMember'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48958
title: 'Team #GoldMember Blog, from Bronze Software Labs.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf0f3'
    - '#020403'
    - '#96d435'
    - '#784905'
    - '#27919f'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
